services:
  auth-db:
    image: mariadb:11
    environment:
      MARIADB_DATABASE: auth_db
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3307:3306"
    volumes:
      - auth-db:/var/lib/mysql
      - ./services/auth-service/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  patient-db:
    image: mariadb:11
    environment:
      MARIADB_DATABASE: patient_db
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3308:3306"
    volumes:
      - patient-db:/var/lib/mysql
      - ./services/patient-service/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  patient-service:
    build:
      context: ./services/patient-service
      dockerfile: DockerFile
    environment:
      CI_ENVIRONMENT: development
      app.baseURL: http://localhost:8000/
      database.default.hostname: patient-db
      database.default.database: patient_db
      database.default.username: root
      database.default.password: root
      database.default.DBDriver: MySQLi
      database.default.DBPrefix: ""
      database.default.port: 3306
      JWT_ACCESS_SECRET: 48b049b3f7d51ce73feb4820436d7091785e41f48c51327c9bd22dca581f2659
    ports:
      - "8000:80"
    depends_on:
      - patient-db

  appointment-db:
    image: mariadb:11
    environment:
      MARIADB_DATABASE: appointment_db
      MARIADB_ROOT_PASSWORD: root
    ports:
      - "3309:3306"
    volumes:
      - appointment-db:/var/lib/mysql
      - ./services/appointment-service/schema.sql:/docker-entrypoint-initdb.d/schema.sql:ro

  phpmyadmin:
    image: phpmyadmin:latest
    ports:
      - "8080:80"
    environment:
      - PMA_HOSTS=auth-db, patient-db, appointment-db
      - PMA_PORT=3306
      - PMA_USER=root
      - PMA_PASSWORD=root
    depends_on:
      - auth-db
      - patient-db
      - appointment-db

volumes:
  auth-db:
  patient-db:
  appointment-db:
  phpmyadmin:
